NUMPY 

In [4]:
import numpy as np

In [5]:
a = [1,2,3,4,5,6]
arr = np.array(a)

In [6]:
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
arr.max()

6

In [8]:
arr.min()

1

In [9]:
arr.mean()

3.5

In [10]:
arr.sum()

21

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
#This will generate an array of zeros
#Pass in a tuple for custom dimensions or a single number for one row
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#This will generate an array of ones
#Pass in a tuple for custom dimensions or a single number for one row
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
#This will generate an identity matrix
#Pass in a number since in identity matrix, nrows and ncolumns are same
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [15]:
#For a matrix, cast a list of lists
a1 = [[1,2,3],[4,5,6],[7,8,9]]
arr1 = np.array(a1)

In [16]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
#np.arange(0,10,2)
#It will start from 0, upto but excluding 10 and in steps of 2
A1 = np.arange(0,10,2)

In [18]:
A1

array([0, 2, 4, 6, 8])

In [19]:
#Linspace returns evenly spaced points between any two numbers
#np.linspace(0,5,10), so it will return 10 evenly spaced points between 0 and 5
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [20]:
#Create an array of the given shape and populate it with random samples from a uniform distribution over [0,1)
#Here pass in dimensions direct instead of using a tuple
np.random.rand(2,5)

array([[0.97458468, 0.70882257, 0.64839589, 0.29865413, 0.64993969],
       [0.81837248, 0.18156091, 0.67428618, 0.97737843, 0.57163786]])

In [21]:
#Return a sample (or samples) from the "standard normal" distribution
np.random.randn(5,5)

array([[ 0.12417923,  1.64313224, -0.60822037,  1.29285741,  1.06841105],
       [-0.46479216, -0.83953095, -0.37597429,  0.22116601,  0.01264982],
       [ 0.93454198,  0.1753642 , -0.17979654, -0.11362053, -0.5945968 ],
       [-1.09020452, -1.60477942,  0.00996961, -1.02868222,  0.94052969],
       [ 0.26704779,  1.73857722,  0.36742651,  1.54486282,  0.47488324]])

In [22]:
#Randint gives you a number between the low and the high. 
print(np.random.randint(0,100))
#However to get 'n' count of numbers between 0 and 100, enter a third argument 
np.random.randint(0,100,10)

38


array([ 3,  1,  3, 96, 78, 73, 43, 77, 79, 14])

In [23]:
#You can use .max(), .min(), .reshape(), .mean(), .argmin(), .argmax()

In [24]:
#Example
sample1 = np.arange(0,25)

In [25]:
sample1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
sample1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
sample1.max()

24

In [28]:
sample1.min()

0

In [29]:
#Argmax and Argmin returns index location of max and min

In [30]:
#Now we will learn about indexing and selection
#Its similar to indexing of a list
arr = np.arange(0,11)

In [31]:
#To reverse the array
arr[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [32]:
#To pick a specific section
arr[0:5]

array([0, 1, 2, 3, 4])

In [33]:
arr[0:5]=100
#What it will exactly do is return 0,1,2,3,4 elements as 100, i.e it will project the values as 100 

In [34]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [35]:
#Now we will index 2D arrays or Matrix
a1 = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [36]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#Now the format of indexing is extremely simple all you have to do is understand
#arr[row,col]
a1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [38]:
a1[1:,1:]

array([[5, 6],
       [8, 9]])

In [39]:
#In order to grab individual Element
#Pass in the coordinates of the element
#arr[row][col]
a1[2][1]

8

In [40]:
a = np.arange(0,10)

In [41]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
#For conditional selection
#This will return a bolean array
#This means, where the condition is false, it will return false and where its true, it will return true
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [43]:
#However if you want the elements and not the boolean values
a[a>5]

array([6, 7, 8, 9])

In [44]:
#NUMPY ARRAY OPERATIONS
arr1 = np.arange(0,10)

In [45]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr1 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [47]:
arr1 + arr1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [48]:
arr1 * arr1

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [49]:
arr1**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [50]:
np.sqrt(arr1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
#UNIVERSAL ARRAY FN
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])